# Generated by Django 3.0.5 on 2020-04-23 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('article_content', models.TextField()),
                ('type', models.CharField(choices=[('Sports', 'Sports'), ('News', 'News'), ('Music', 'Music'), ('Business', 'Business')], default='News', max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('uploaded_on', models.DateField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_app.Login')),
            ],
        ),
    ]
