# Generated by Django 3.1.1 on 2020-09-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_article_tags_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_tags',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='article_tags',
            old_name='tags_id',
            new_name='tags',
        ),
    ]
