# Generated by Django 3.1.1 on 2020-09-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0005_auto_20200918_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Post_Category',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_app.post_category'),
        ),
    ]
